# Generated by Django 4.2.16 on 2025-08-17 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('key', models.CharField(choices=[('FIRST_LOG', 'First Drop in the Bucket'), ('THREE_DAY_STREAK', 'Getting Started'), ('SEVEN_DAY_STREAK', 'Weekly Warrior'), ('THIRTY_DAY_STREAK', 'Monthly Master'), ('TENTH_LOG', 'Diligent Logger'), ('FIFTIETH_LOG', 'Super Scrivener'), ('GOAL_SETTER', 'Dreamer'), ('GOAL_ACHIEVER', 'Goal Getter!'), ('CATEGORY_EXPLORER', 'Organizer')], max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_currency', models.CharField(default='USD', max_length=10)),
                ('monthly_savings_goal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_log_date', models.DateField(blank=True, null=True)),
                ('streak_count', models.IntegerField(default=0)),
                ('last_password_change', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('university', models.CharField(default='No university added', max_length=20)),
                ('achievements', models.ManyToManyField(blank=True, to='accounts.achievement')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_description', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Activities',
                'ordering': ['-timestamp'],
            },
        ),
    ]
